version: '3.8'

services:
  web:
    build:
      context: ./src
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=qwerty
      - DATABASE_NAME=db
    depends_on:
      - db
    networks:
      - web-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - web-network
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwerty
    volumes:
      - db_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./mysql-config:/etc/mysql/conf.d
networks:
  web-network:
volumes:
  db_data:

