version: '3.8'

services:
  web:
    build:
      context: ./src
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=qwerty
      - DATABASE_NAME=database
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwerty
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

